env: "local"
db:
  host: "prtf-stream-postgres"
  port: "5490"
  username: "postgres"
  password: "postgres"
  dbname: "postgres"
  sslmode: "disable"
rdb:
  host: "prtf-stream-redis"
  port: "6379"
  password: "redis"
  db: 0
http:
  port: 8092
  timeout: 5s
