env: "local"
migrationPath: "migrations"
db:
  host: "prtf_auth_postgres"
  port: "5432"
  username: "postgres"
  password: "postgres"
  dbname: "postgres"
  sslmode: "disable"
http:
  port: 8084
  timeout: 5s
accessTokenTtl: 24h
refreshTokenTtl: 72h
