env: "prod"
migrationPath: "migrations"
db:
  host: "prtf-auth-postgres"
  port: "5432"
  username: "postgres"
  password: "postgres"
  dbname: "postgres"
  sslmode: "disable"
http:
  port: 8084
accessTokenTtl: 10m
refreshTokenTtl: 72h
