include:
  - ../auth/sso/docker-compose.yml
  - ../quiz/docker-compose.yml

services:
  nginx:
    build:
      context: .
    networks:
      - prtf_gateway_network
    ports:
      - "80:80"
    deploy:
      restart_policy:
        condition: on-failure

networks:
  prtf_gateway_network:
