development:
  dialect: postgres
  database: postgres
  user: postgres
  password: postgres
  host: 127.0.0.1
  port: 5436
  pool: 5

test:
  url:
    {
      {
        envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/myapp_test",
      },
    }

production:
  url:
    {
      {
        envOr "DATABASE_URL" "postgres://postgres:postgres@192.168.11.13:5432/myapp_production",
      },
    }
