services:
  prtf-quiz-server:
    depends_on:
      - prtf-quiz-postgres
    build:
      context: .
    container_name: prtf-quiz-server
    hostname: prtf-quiz-server
    networks:
      - prtf-quiz-net
    ports:
      - 8086:8086
    volumes:
      - prtf-quiz-server-volume:/app
    deploy:
      restart_policy:
        condition: on-failure
  prtf-quiz-postgres:
    image: postgres
    container_name: prtf-quiz-postgres
    hostname: prtf-quiz-postgres
    networks:
      - prtf-quiz-net
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:?database password not set}
    ports:
      - 5436:5432
    volumes:
      - prtf-quiz-postgres-volume:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  prtf-quiz-postgres-volume:
  prtf-quiz-server-volume:

networks:
  prtf-quiz-net:
    driver: bridge
