services:
  prtf_quiz_server:
    depends_on:
      - prtf_quiz_postgres
    build:
      context: .
    container_name: prtf_quiz_server
    hostname: prtf_quiz_server
    networks:
      - prtf_quiz_net
    ports:
      - 8086:8086
    volumes:
      - prtf_quiz_server_volume:/home/app
    deploy:
      restart_policy:
        condition: on-failure
  prtf_quiz_postgres:
    image: postgres
    container_name: prtf_quiz_postgres
    hostname: prtf_quiz_postgres
    networks:
      - prtf_quiz_net
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:?database password not set}
    ports:
      - 5436:5432
    volumes:
      - prtf_quiz_postgres_volume:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  prtf_quiz_postgres_volume:
  prtf_quiz_server_volume:

networks:
  prtf_quiz_net:
    driver: bridge
