global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prtf-docker-containers"
    static_configs:
      - targets: ["prtf-cadvisor:8080"]
  - job_name: "prtf-stream-nginx"
    metrics_path: /metrics
    static_configs:
      - targets: ["prtf-nginx-exporter:9113"]
  - job_name: "prtf-host-metrics"
    static_configs:
      - targets: ["prtf-node-exporter:9100"]
  - job_name: "prtf-stream-server"
    static_configs:
      - targets: ["prtf-stream-server:8092"]
  - job_name: "prtf-stream-client"
    static_configs:
      - targets: ["prtf-stream-client:80"]
