services: # Define services here
  web: # The web service...
    image: nginx # ... uses the publicly available nginx image
    volumes: # ... and uses the included nginx.conf for proxy routing
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80" # forward your port 8080 -> internal network's port 80
    depends_on: # Don't start until both alpha and beta are up!
      - alpha
      - beta
  alpha: # The alpha service...
    build: . # ... is built using the Dockerfile in this directory
    ports:
      - "8081:8080"
    environment: # We set this variable, so the service prints out a unique name
      - MESSAGE=alpha
  beta: # The beta service, same as alpha...
    build: .
    ports:
      - "8082:8080"
    environment:
      - MESSAGE=beta
