services:
  prtf_auth_server:
    depends_on:
      - prtf_auth_postgres
    build:
      context: .
    container_name: prtf_auth_server
    hostname: prtf_auth_server
    networks:
      - prtf_auth_net
    ports:
      - 8085:8085
      - 8084:8084
    volumes:
      - prtf_auth_server_volume:/app
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: on-failure
  prtf_auth_postgres:
    image: postgres
    container_name: prtf_auth_postgres
    hostname: prtf_auth_postgres
    networks:
      - prtf_auth_net
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?database password not set}
    ports:
      - 5435:5432
    volumes:
      - prtf_auth_postgres_volume:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  prtf_auth_postgres_volume:
  prtf_auth_server_volume:

networks:
  prtf_auth_net:
    driver: bridge
